steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/node-web-app:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/node-web-app:$COMMIT_SHA']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mydeployment', 'mynode=gcr.io/sit323-23t1-pei-365a95e/webapp:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=jinwei-pei'

